# -*- coding: utf-8 -*-
"""HousePricePredictionEDA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xFrGNlbZnHkh7iAL2u7rinnFBDYf6-bE

# Assignment 2

This assignment mainly enhance your Exploratory Data Analysis Skills. The total mark for this assignment is 40. Answer the questions in the code chrunk and
fill up the missing part of the code.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import boxcox
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge, Lasso
from scipy.special import inv_boxcox
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

## read the datset from your local drive
from google.colab import files
upload = files.upload()

## upload the dataset
import pandas as pd
df = pd.read_csv('train.csv')

## functions that you can use to learn your dataset
df.head(5)
df.info()
df.describe()

#####################################################################
### Exploratory Data Analysis #######################################
# 1. ToDo ###########################################################
#### Answer: Why do I separate continuous and categorical features?
# 1 point
## A: We sepreate continuous and categorical features becausse the Sale Price leads to a continiues number this can now
#be broken up into two different  sections which is continios and catagorical. Also catogogircal can lead to continous but not vise versa.
#this is all very important for data visualioation at the end
#####################################################################
# Creating dataframe for numeric and categorical features separately
# make a note of the select## A: We sepreate continuous and categorical features becausse the Sale Price leads to a continiues number this can now
#be broken up into two different  sections which is continios and catagorical. Also catogogircal can lead to continous but not vise versa.
#this is all very important for data visualioation at the end _dtypes() function, very useful
numeric_df = df.select_dtypes(include=['int64', 'float64'])
categorical_df = df.select_dtypes(include=['object'])

from pandas.core.arrays import categorical
############ToDo####################################################
## 1 points
## find out the feature names of the continuous and categorical var
## find out the dimension of numeric_df and categorical_df

numeric_df.columns
categorical_df.columns

numeric_df.shape
categorical_df.shape

from numpy.ma.core import correlate
######## In linear regression ######################################
## 6 points
### for continuous variables, what should I check first?

## A: For continuous variables you should check first if it is a instant variable or a ration variable

### Last time we mentioned that two situations will lead to fitting
### problems for LR, what are they?
### 1. overfitting
### 2. underfitting
### How to check 1 ?  What visualization technique can you use?
## Use the visualiation technique to create this graph

### Answer my previous question and write down the code below
numeric_df.corr()
plt.figure(figsize=(25,16))

## fill out the misssing code here
correlation = numeric_df.corr()
sns.heatmap(correlation, annot = True)
plt.show()

############ToDo###################################################
## 3 points
## What information can you learn from the plot?
## Which pairs of variables demonstrate high correlation?
##

np.unique(numeric_df["LowQualified"],return_counts = True)

## A: Information we can learn from the plot is which featurees are driving attention in determining a House price and
## from there which features have a good correlation and which deatures do not. This tells us what data is distractig not useful.
## A: GarageYrBlt and YearBuilt also GarageCars and GarageArea are two examples that demosntrate variables with high correlation



## What should we do about them?  Should we keep them or remove them?
## A: We neede to focus our attention on these variables because they show good correlation which then
## helps towards the understanding of any causal relationship
## We should keep them because these pairs of variables will tell us information on House Price Predictions

###################################################################
##### Univariate Data Analysis ####################################
fig=plt.subplots(figsize=(12, 21))
i=0
for feature in numeric_df.columns:
    if feature not in ['Id', 'SalePrice']:
        i+=1
        plt.subplot(13, 3, i)
        sns.distplot(df[feature])
        plt.tight_layout()

## ToDO #############################################################
## Answer the below questions and fill up the code
## 6 points
######### How to find if each univariate variable has strong correlation with
######### the target variable?
##A: We can find it by seeing how big the area under the plot is which can tell us the bigger probability
## that the univariate has a strong correlation with the target variable
### What visualization technique should you use to explore this?
### create the plot here

fig=plt.subplots(figsize=(12, 21))
i=0
for feature in numeric_df.columns:
    if feature not in ['Id', 'SalePrice']:
        i+=1
        plt.subplot(13, 3, i)
        ## fill out the misssing code here
        sns.scatterplot(numeric_df[feature], numeric_df['SalePrice'])


        plt.tight_layout()

"""5 points

What can you learn from the plot?

A: I can see that GarageYrBuilt, EnclosedPorch, GarageArea, WoodDeckSF,
OpenPorchPF, ScreenPorch, and GrLiveArea all show a good correlation  with the SalePrice. You can see the correlation is linear in all these variables
when paired with SalesPrice

Are they are continuous variables?

A: Not all of them are

If not, which ones are categorical variables?

A: KitcehnAbv, GarageCars, FullBath, HalfBatch, Fireplaces, YrSold
MoSold,OvrQual,OvrCond, BsmtFullBath, BsmtHalfaBath


Do you find some variables that only have one unique value?

Are there any potential problems with this when you fit linear regression


"""

#######ToDo###################################################
## 6 points
## Fill up the code and answer the questions "What can you learn from the graph"
### Since there are categorical variable in the scatter plot,
### To learn the relationship between the categorical variable and the target
### Which visualization technique is more appropriate other than the plot we use
### in the previous code chrunk
###['MSSubClass','OverallQual','OverallCond','MoSold','YrSold','BsmtFullBath','FullBath','HalfBath','BedroomAbvGr','TotRmsAbvGrd','Fireplaces']

fig=plt.subplots(figsize=(12, 12))

for i, feature in enumerate(['MSSubClass','OverallQual','OverallCond','MoSold','YrSold','BsmtFullBath','FullBath','HalfBath','BedroomAbvGr','TotRmsAbvGrd','Fireplaces']):
    plt.subplot(6, 3, i+1)
    ## Which graph should I use A:Boxplot
    ## fill up the code below
    sns.boxplot(numeric_df[feature], df['SalePrice'])
    plt.tight_layout()

### What can you learn from the graph?
### 1. 'OverallQual'  A: Postive Linear Regression meaning the better OVerallQuAL THE BETTER THE SALE PRICE
### 2. 'OverallCond'  plateau once you get to a OVerallcondition of 5 for the most part
### 3. 'MoSold' and 'YrSold'  A: Stays the same The value does not really change as both x variables both go up meaning they both play no effect in Sale price
### 4. 'FullBath' = 3 and 'HalfBath' = 1   A: FulBath at 3 produceds the highest sale price while Halfbath at 1 does the same
### 5. 'TotRmsAbvGrd'   A: Linear regression but it begins to plateau once it hits 11 meaning 11 is the max benifit you going to see

# Converting the year related features into number of years
for feature in ['GarageYrBlt','YearBuilt','YearRemodAdd', 'YrSold']:
    df[feature] = 2022 - df[feature]

### Find the categorical variable names
categorical_df.columns.sort_values()

### So many variables, can I put some of the variables into different subclasses?
bsmt_df = categorical_df[['BsmtCond', 'BsmtExposure', 'BsmtFinType1','BsmtFinType2', 'BsmtQual']]
garage_df = categorical_df[['GarageCond','GarageFinish', 'GarageQual', 'GarageType']]
sale_df = categorical_df[['SaleCondition', 'SaleType']]
exterior_df = categorical_df[['ExterCond', 'ExterQual', 'Exterior1st', 'Exterior2nd']]
heating_df = categorical_df[['Heating', 'HeatingQC','Electrical','FireplaceQu']]
land_df = categorical_df[['LandContour', 'LandSlope', 'Street', 'Alley','PavedDrive', 'Fence']]

##########ToDO##################################################################
## 6 points
## fill up the code and answer the question below
fig=plt.subplots(figsize=(10, 10))

for i,col in enumerate(bsmt_df.columns):
    plt.subplot(3, 2, i+1)

    ## fill up the code below
    sns.countplot(bsmt_df[col])
    plt.tight_layout()

#### What can we learn from the characteristics of the basements in all the houses?
## The GD and TA are thew most important charectartics seen in each house
#### Answer this question

#### If you do not understand the meaning of the variable, check up your data
#### dictionary.

### ToDO ###########################################################################
#### Fill up the code below and anser the questions
#### 6 points
### How do you examine the relationship between sale price and all basedment related variables?

##A: I would look at the median and mean areas between all the related variables becuase this on average will tell me where most of the each
## basement data is focused around and then comapre those numbers to the saleorice. Rather than lookin at the outliers and the min and max's
## which would essentially tell me nothing i need to know

### Which data visualization technique is appropriate?

fig=plt.subplots(figsize=(10,10))

for i,col in enumerate(bsmt_df.columns):
    plt.subplot(3, 2, i+1)
    sns.boxplot(bsmt_df[col],df['SalePrice'])
    ## fill up the code here


    plt.tight_layout()

"""# Student Reflection (not this part of the assignment but for in-class activity)
Based on what we have done? Can you conduct a similar analysis
for garage, sale, exterior, heating and land features (garage_df, sale_df, exterior_df, heating_df, land_df)?

# 5-10 volunteers, serve as 2 points out of 100 in our final grades. Write you own code and demonstrate it and your findings in class. (If students are very enthusiastic, two students can form one group and do presentations together)

"""