# -*- coding: utf-8 -*-
"""ShoeGrades

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LgNtaqGKApnVNxLM1qA5r4OzpbYWoHZE
"""

class Shoe:


  def __init__(self,brand,color,style):
    self.brand = brand
    self.color = color
    self.style = style




  def score(self,mybrand,mycolor,mystyle):
    a = self.brand
    b = self.color
    c = self.style

    brand_value = 0
    color_value = 0
    style_value = 0
    popularity = 0


    if a =="jordan":
      brand_value = 2
    elif  a =="addidas":
      brand_value = 3
    elif  a =="nike":
      brand_value = 4
    else:
      brand_value = 1

    if b == "white":
      color_value = 2
    elif b == "grey":
      color_value = 3
    elif b == "black":
      color_value = 4
    else:
      color_value = 1

    if c == "lowtop":
      style_value = 2
    if c == "midtop":
      style_value = 3
    if c == "hightop":
      style_value = 4
    else:
      style_value = 1



    if mybrand == a:
      popularity = popularity+3
    if mycolor == b:
      popularity = popularity+3
    if mystyle == c:
      popularity = popularity+3




    final_score = brand_value + color_value +style_value +popularity

    return final_score

def reccomandation(shoes,mybrand,mycolor,mystyle):

  topShoe= shoes[0]
  topScore = 0

  for n in shoes:
    if n.score(mybrand,mycolor,mystyle) > topScore:
      topScore = n.score(mybrand,mycolor,mystyle)
      topShoe = n

  return topShoe

myfavoritebrand = "nike"
myfavoritecolor = "green"
myfavoritestyle = "midtop"

s1 = Shoe("nike", "white","hightop")
s2 = Shoe("jordan", "blue","lowtop")
s3 = Shoe("addiaas", "black","mid")
s4 = Shoe("nike", "grey","lowtop")
s5 = Shoe("rebok", "red","lowtop")
s6 = Shoe("nike", "green","midtop")


print(s1.score(myfavoritebrand,myfavoritecolor,myfavoritestyle))

myshoes = [s1,s2,s3,s4,s5,s6]

a = reccomandation(myshoes,myfavoritebrand,myfavoritecolor,myfavoritestyle)
print(a.brand)
print(a.style)
print(a.color)
print(s6.score(myfavoritebrand,myfavoritecolor,myfavoritestyle))